### ISSUE TITLE
Hint mode

### ISSUE THREAD

**Issue by ergpopler** [antoyo/titanium#26]
Hint mode would be nice, where you can press a button such as 'f' and have it show you the number to click on different places of the website like in 'Vimb'

**Comment by antoyo** [comment]
That's already the main feature of the browser, isn't it? (Unless you're talking about something else.)

You're talking about something like [this image in the readme](https://github.com/antoyo/titanium/blob/master/doc/screenshots/titanium-follow-links.png)?

**Comment by ergpopler** [comment]
yes it doesn't work for me i guess? what is the binding?

precisely like that picture yes.

**Comment by antoyo** [comment]
Maybe the config was not created properly? Can you look at you file `~/.config/titatium/keys` to see if it contains:
```
nmap f follow
```
Also, running the browser in a terminal window with logs `titanium --log` could provide a hint about what is going on.

Maybe the CSS for the hints (`~/.config/titanium/stylesheets/hints.css`) was not created properly?

**Comment by ergpopler** [comment]
i'll check this out in a bit.

**Comment by antoyo** [comment]
Please reopen if you still have this issue.
