### ISSUE TITLE
Web process failing to render(Crash) while entering youtube

### ISSUE THREAD

**Issue by Tryware** [antoyo/titanium#35]
I'm testing the browser and i experienced crashes while entering websites like youtube 

```
** (titanium:532): CRITICAL **: 20:51:07.876: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed

** (titanium:532): CRITICAL **: 20:51:07.963: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:3410): GLib-GObject-WARNING **: 20:51:08.792: invalid (NULL) pointer instance

(WebKitWebProcess:3410): GLib-GObject-CRITICAL **: 20:51:08.792: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

it happens with almost any website that involves video streaming (i tested it on pornhub, xvideos, twitch and youtube)

**Comment by antoyo** [comment]
Have this ever worked for you?

By crash, do you mean you see the red alert "The web process crashed." or you mean something else (browser suddently exit, rust panic, segfault)?

Also, it looks like you need to install gstreamer, which will be needed to watch videos.

Not sure for the other errors, but we can start with that.

**Comment by Tryware** [comment]
> 
Yeah, it shows the red alert "The web process crashed"
gstreamer is already installed. Any web process that involves videos doesn't works

**Comment by antoyo** [comment]
Can you try with any other webkit2gtk web browser and see if it works?

Also, it might help if you could post a stacktrace of the crash.

**Comment by Tryware** [comment]
OH SORRY FOR TAKING TOO MUCH TO ANSWER

Everything is normal now, i installed  the unstable webkit2gtk to fix it
